### ISSUE TITLE
When draw, it isn't a draw

### ISSUE THREAD

**Issue by gimilt** [davidseanlittlewood/BeatTheBotsServer#4]
I had a fight with the bot where we had health being reduced equally. Yet one side won and it didn't end as a draw
![image](https://user-images.githubusercontent.com/44804769/48062265-372adf00-e1ca-11e8-8ce5-a8bc59bc34b2.png)

**Comment by ardliath** [comment]
Hi

In the event that both bots run out of health in the same turn or the bots become locked (both fail to do damage for about 50 consecutive turns) the game tries to decide a winner.

It will take damage into account first (obviously in your case both have lost all their health). Then it will take progress into account. In the screenshot above "GG" has made more progress across the arena than "Dolly" so although both ran out of health GG got the victory.

I'll see if I can improve the victory message to give a hint of how they won!
