### ISSUE TITLE
Enabled flag do not work

### ISSUE THREAD

**Issue by gimilt** [davidseanlittlewood/BeatTheBotsServer#5]
I had only two bots enabled, yet 3 of them participated in fights. They were all on the leaderboard, so probably it used a list from there.

**Comment by gimilt** [comment]
I have cleared down the leaderboard and it didn't help

**Comment by gimilt** [comment]
I have cleared down the leaderboard and it didn't help. Sorry for an incorrect closure :)

**Comment by ardliath** [comment]
I suspect this is because the tickboxes aren't saved until you click out/close the app/do a rain dance...

I'll double check and see if we can improve it

**Comment by davidseanlittlewood** [comment]
I don't think this is a bug it's an inelegant design.  When you change the details in the grid including the enabled bots the grid changes to edit more.  When you click on a different row the change is committed.   The work around is to check the enabled and disabled bots and then click on any cell in the grid.

I'll look to see how easy this will be to improve.
