### ISSUE TITLE
Crash when remote bot is not running.

### ISSUE THREAD

**Issue by davidseanlittlewood** [davidseanlittlewood/BeatTheBotsServer#8]
Add a non house bot to your list of bots and stop it running before or part way through a game and the server crashes.

The expected behaviour is that a non contactable bot forfeits it's move but is given an opportunity to recover during the game.

The issue seems to have resolve itself but I'll keep trying to re-create.

**Comment by ardliath** [comment]
I have a theory

While working on another issue this line in MainForm errored:

                    var winner = arena.Winner;
                    var loser = arena.Bots.Except(new Bot[] { winner }).Single();

In the line

if (!string.IsNullOrWhiteSpace(game.Winner))

game.Winner was not null but

arena.Winner was

This threw a null reference

I wonder if victory is being given to one property and not the other...
